version: '3'

services:
    rabbitmq:
        hostname: rabbit
        command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
         mage: rabbitmq
        environment:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin
        ports:
          - 5672:5672
          - 15672:15672
        
    order:
        build: ./Order
        depends_on:
            - rabbitmq

    book:
        build: ./Product_Book
        depends_on:
            - rabbitmq

    eletronic:
        build: ./Product_Eletronic
        depends_on:
            - rabbitmq
           
    splitter:
        build: ./Splitter
        depends_on:
            - rabbitmq
            
    aggregator:
        build: ./Aggregator
        depends_on:
            - rabbitmq