version: '3.4'

services:
  aggregator:
    image: aggregatorservice
    build:
      context: .
      dockerfile: Service/Dockerfile
    environment:
      - RabbitMQHostName=http://host.docker.internal:15672
    extra_hosts:
      - "localhost:10.30.10.157"