FROM microsoft/dotnet:2.2.100-sdk AS build
WORKDIR /app
COPY . ./
RUN dotnet restore Aggregator.sln -nowarn:msb3202,nu1503
RUN dotnet publish Aggregator.sln --no-restore -c Release -o /app

FROM microsoft/dotnet:2.2.0-aspnetcore-runtime
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "Service.dll"]