version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        ports: 
            - "15670:15672"
            - "5670:5672"

    order:
        build: ./Order
        depends_on:
            - rabbitmq

    validationa:
        build: ./ValidationA
        depends_on:
            - rabbitmq

    validationb:
        build: ./ValidationB
        depends_on:
            - rabbitmq
    
    validationc:
        build: ./ValidationC
        depends_on:
            - rabbitmq